sudo: false

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack/
  - $HOME/.local/bin/
  - .stack-work/

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

jobs:
  include:
    - stage: stack test
      script: stack --no-terminal test --haddock --no-haddock-deps
      stage: site build test
      script: stack exec site rebuild
